title:   Colby D. Lalicker
logo: assets/img/circleme.jpg
description: [Resume Download](//drive.google.com/uc?export=download&id=1cj4J2plKvLsp-kDDmzqR8T2-rmR4YTMP)
show_downloads: true
theme: jekyll-theme-minimal
